name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.2.5
        with:
          hostname: 'https://tondomaine.com'
          cPanelApiPort: '2083'
          cpanel_username: 'TON_USERNAME_CPANEL'
          cpanel_token: '${{ secrets.CPANEL_TOKEN }}'
          repository_root: '/home/e2378268/repositories/nom-de-ton-repo'
          branch: main
